### ISSUE TITLE
[Request] - add config file name (and version) to out.csv

### ISSUE THREAD

**Issue by acfischer42** [TheoTechnicguy/CIS_Win#12]
**Is your feature request related to a problem? Please describe.**
when testing different versions of the config file it would be good to know the name and possibly version in the config file.

**Describe the solution you'd like**
add config file name and version to the header of the out.csv

**Comment by TheoTechnicguy** [comment]
Can you look if the new commits are what you requested?

**Comment by acfischer42** [comment]
thanks
