### ISSUE TITLE
[Request] - Add feature to read registry value and evaluate result - 

### ISSUE THREAD

**Issue by acfischer42** [TheoTechnicguy/CIS_Win#3]
HKEY_USERS\[USER SID]\Software\Policies\Microsoft\Assistance\Client\1.0:NoImplicitFeedback should be set to enabled.

Powershell CMD: 

(Get-ItemProperty   -Path HKCU:\Software\Policies\Microsoft\Assistance\Client\1.0 -Name   "NoImplicitFeedback").NoImplicitFeedback

will return the value of the key. Note the () and the repetition of the key name.

Value = 1 enumerates to Enabled (to be confirmed)

HKCU
HKLM

**Comment by TheoTechnicguy** [comment]
This [commit](https://github.com/TheoTechnicguy/CIS_Win/commit/5976e3f377b7ffaf249850ed9a36e3487d8216d0) contains the feature. It will be included in the next release!
