### ISSUE TITLE
[Bug] - if registry key is not found error is created

### ISSUE THREAD

**Issue by acfischer42** [TheoTechnicguy/CIS_Win#4]
**Describe the bug**
if a registry key is entered in Config file, but that reg key does not exist in registry, program throws an error

**Expected behaviour**
a Non existing reg key = default setting of value and is equal to 0 or none in expected results column.

**Screenshots and files**
__main__.ConfigError: Cannot find policy HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\MicrosoftEdge\SearchScopes\ShowSearchSuggestionsGlobal. Verify spelling in the CF.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - CIS_Win version: dev 0.1.3
 - Distribution: / py
 - if py, branch: dev

**Additional context**

**Comment by TheoTechnicguy** [comment]
Issue is fixed @acfischer42. It will be available in release 0.1.3.
