### ISSUE TITLE
[Request] - add config file line number (or control number) to error messages 

### ISSUE THREAD

**Issue by acfischer42** [TheoTechnicguy/CIS_Win#5]
**Is your feature request related to a problem? Please describe.**
while testing it is not always sure which value is returned from registry. for example it could be YES or 1. 
if using 1 and type int following error occurs:

 to_csv.append(int(policy_values) == int(row_dict["exact_val"])) # compliance
ValueError: invalid literal for int() with base 10: 'yes'

The error itself is valid, but it would be easier to trace back to the entry in config file if line number of config file would be available. 

**Describe the solution you'd like**
include row counter or similar in console output while running.

**Describe alternatives you've considered**

**Additional context**

**Comment by TheoTechnicguy** [comment]
It is in progress. Can you make the config row available so I can test the fix?
